In [19]:
import tensorflow as tf
import numpy as np
import pprint

### 1. Simple 1D array and slicing

<b>rank</b> : Dimension of array<br>
<b>shape</b> : Appearance of aaray / Contained element

<b>slicing</b> : Split array

In [20]:
# 1D Array

t = np.array([0., 1., 2., 3., 4., 5., 6.])

print(t)

# Indexing array
print(t[-1]) # array t's last index

# Slicing array
print(t[:3]) # array t's #0~2
print(t[:-1]) # array t's #2~last-1

[0. 1. 2. 3. 4. 5. 6.]
6.0
[0. 1. 2.]
[0. 1. 2. 3. 4. 5.]


### 2. 2D Array

Like 1D array, rank, shape, indexing and slicing are possible.

In [21]:
# 2D Array

pp = pprint.PrettyPrinter(indent=4)
 
t2 = np.array([[0., 1., 2.],[3., 4., 5.],[6., 7., 8.],[9., 10., 11.],[12., 13., 14.]])

pp.pprint(t2)

print(t2.ndim) # check t2' rank
print(t2.shape, end = "\n\n") # check t2's shape

# Indexing array
print(t2[1 ,2])

# Slicing array
print(t2[:,2]) # Column 2's all index
print(t2[0,:]) # Row 0's all index

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])
2
(5, 3)

5.0
[ 2.  5.  8. 11. 14.]
[0. 1. 2.]


### 3. Matmul vs Multiply

When multiplying an array, the shapes must match.<br>
The last shape of the previous array and the first shape of the rear array must match.

The product of an array is represented using the <b>Matmul</b> function.<br>
Using the <b>* operator</b>, which we commonly use for multiplication, yields values other than the product of arrays.

In [29]:
# Matmul vs Multiply

matrix1 = tf.constant([[1, 2],[3, 4]])
matrix2 = tf.constant([[1],[2]])

print('Matrix1  shape:', matrix1.shape)
print('Matrix2  shape:', matrix2.shape, end = "\n\n")

# Matmul arrays
print("Matmul example")
print(tf.matmul(matrix1, matrix2).numpy(), end="\n\n")

# Multiply arrays
print("Multiply example")
print((matrix1 * matrix2).numpy())

Matrix1  shape: (2, 2)
Matrix2  shape: (2, 1)

Matmul example
[[ 5]
 [11]]

Multiply example
[[1 2]
 [6 8]]


### 4. Broadcasting

<b>Broadcasting</b> automatically calculates and calculates shapes when they do not match the shape of the array.<br>

<b>Boradcasting is convenient, but if you don't check the shape correctyl, you might get incorrect results.</b>

In [31]:
# Broadcasting

# When shape is correct
matrix1 = tf.constant([3, 3])
matrix2 = tf.constant([3, 3])
print((matrix1 + matrix2).numpy(), end="\n\n")

# When shape is different - automatically broadcasting
matrix1 = tf.constant([3, 6])
matrix2 = tf.constant([10])
print((matrix1 + matrix2).numpy(), end="\n\n")

[6 6]

[13 16]



### 5. Reduce mean and Reduce sum

<b>Reduce mean & sum</b> is affected by data types.<br>

If the array is int type, <b>Reduce mean & sum</b> are also printed as int type. Therefore, when using <b>Reduce mean & sum</b>, you should use float point.

In [43]:
# Reduce mean and Reduce sum

# Reduce mean
print("Reduce mean")

# When using int type
print(tf.reduce_mean([1, 2], axis =0).numpy())

# When using float type
x = [[1., 2.],[3., 4.,]]
print(tf.reduce_mean(x).numpy(), end="\n\n")

# Reduce sum
print("Reduce sum")

# array x's sum
print(tf.reduce_sum(x).numpy())
# array axis -1's sum and mean
print(tf.reduce_mean(tf.reduce_sum(x, axis = -1)).numpy())

Reduce mean
1
2.5

Reduce sum
10.0
5.0


### 6. Argmax

<b>Argmex</b> returns the position of the element with the largest value along the axis we set.

In [44]:
# Argmax

x = [[0, 1, 2],
    [2, 1, 0]]

# axis 0's max value's index
print(tf.argmax(x, axis = 0).numpy())

# axis -1's max value's index
print(tf.argmax(x, axis = -1).numpy())

[1 0 0]
[2 0]


### 7. Reshape

<b>Reshape</b> changes the shape of the array to the shape we want.<br>

-1 of the shape means that the computer will arrange it autonomously.

<b>squeeze</b> : Combining dimensions of an array into one.
<b>expand</b> : Increasing the dimensions of an array.

In [53]:
# Reshape

t = np.array([[[0, 1, 2],
              [3, 4, 5]],
             [[6, 7, 8],
             [9, 10, 11]]])

# t's shape
print(t.shape, end = "\n\n")

# reshape array t
print(tf.reshape(t, shape = [-1, 3]).numpy(), end = "\n\n")

# reshape array t
print(tf.reshape(t, shape = [-1,1, 3]).numpy(), end = "\n\n")

# squeeze
print(tf.squeeze([[0], [1], [2]]).numpy(), end = "\n\n")

# expand
print(tf.expand_dims([0 ,1 ,2], 1).numpy())

(2, 2, 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]

[0 1 2]

[[0]
 [1]
 [2]]


### 8. One-hot

<b>One-hot</b> is expression, which the index position to be expressed is 1, and otherwise is 0.

In [54]:
# One-hot

print(tf.one_hot([[0], [1],[2]], depth = 3).numpy())

[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]]


In [55]:
t = tf.one_hot([[0], [1], [2], [0]], depth = 3).numpy()
print(tf.reshape(t, shape = [-1, 3]).numpy())

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


### 9. Casting

<b>Casting</b> is chane the data type of the elements which in arrays.

In [56]:
# Casting

# Change float to int
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).numpy()

array([1, 2, 3, 4])

In [57]:
# Change boolean to int
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).numpy()

array([1, 0, 1, 0])

### 10. Stack

In [58]:
# Stack

x = [1, 4]
y = [2, 5]
z = [3, 6]

# Stack three arrays
tf.stack([x, y, z]).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
# Stack three arrays and axis is 1
tf.stack([x, y, z], axis = 1).numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
# Stack three arrays and axis is 0
tf.stack([x, y, z], axis = 0).numpy()

array([[1, 4],
       [2, 5],
       [3, 6]])

### 11. Ones and Zeros like

<b>Ones and Zeros like</b> is used when you want to get an array filled with 0 or 1 values while retaining the shape of an array.

In [61]:
# Ones and Zeros like

x = [[2, 1, 0],
    [0, 1, 2]]

# fill array with 1
tf.ones_like(x).numpy()

array([[1, 1, 1],
       [1, 1, 1]])

In [62]:
# fill array with 0
tf.zeros_like(x).numpy()

array([[0, 0, 0],
       [0, 0, 0]])

### 12. Zip

If you use <b>zip</b>, then you can handle multiple arrays at once.

In [64]:
# Zip

for x, y in zip([1,2,3], [4,5,6]):
    print(x, y)
    
print()
    
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6

1 4 7
2 5 8
3 6 9
